fieldLayouts:
  481667e9-a072-4702-9f0d-913861b4678d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c53c9878-934b-499b-9b7b-a1f997beeab8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 995e3fa2-79e4-4d45-b6c4-1ec9290e2565 # banner Img
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 435c952d-3073-4d4d-bcfc-e2f06efca695
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 736af702-524f-4e78-847e-7edf2f0595e7 # rich text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e8e664e-fc65-4a27-8585-ed04442b5574
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d7a4b940-1a16-4ce8-9c06-fc4744700f2f # kaart
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f0f424f-0e7b-4379-8d86-3a1df7e22b57
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 038448cc-04cb-440a-8ae4-bc992054deef
        userCondition: null
handle: contactPage
hasTitleField: false
name: 'contact page'
section: e9de2868-b149-4496-abec-9a499111e979 # contact page
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
