fieldLayouts:
  8b489f41-11c7-4531-aa88-ecae3a42d4e3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 492001d0-cd0b-471e-a2ef-be6e80ba6cc4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 736af702-524f-4e78-847e-7edf2f0595e7 # rich text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c18f7058-01ce-4a11-949e-ad44daf03919
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6938681d-362d-44d9-a5f7-1c98e89515fd
        userCondition: null
handle: default
hasTitleField: false
name: Default
section: e7157de2-249e-4e6f-b6b0-cdcc6bb2eb41 # blog
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: 'club in de kijker'
titleTranslationKeyFormat: null
titleTranslationMethod: site
