fieldLayouts:
  8f9c10fb-9939-440f-974f-ff1475aa3d7f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cd05b136-8e5f-47ce-9255-ec93668202a3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7e6ae166-ec92-43a6-a2cf-9eb6d803c865
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: eba129b7-7efe-47d0-af12-44808f369268 # store Categories
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
