fieldLayouts:
  46a399c4-1f9c-4df3-99e4-9fc7e43777f7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 060cff9c-c6ba-4bdf-881d-e5c46b18d5f5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 995e3fa2-79e4-4d45-b6c4-1ec9290e2565 # banner Img
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ea518d4-d6b8-4530-8710-5b1923bfe903
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d1e9aa0c-025f-4dbc-a8a3-b9586b665d8b # naam teamlid
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44051440-0a83-4460-bac3-15de7ab8ffa8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 389a23e5-8e26-48b6-84e3-846b233734c2 # email adres teamlid
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a7ad949-9a38-4b6f-a0df-a2ddd183b1cf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d5d031aa-034a-47d7-9720-7952304ecc4e # korte eigen tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd70f886-10a8-4ff4-bad2-0f081187f175
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 11178d46-81a5-48fe-9619-d4cc4092bbad
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 0b72464e-f816-431d-a30b-e7df165c2367 # team
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
