columnSuffix: vnwxzujm
contentColumnType: text
fieldGroup: bf54c795-76da-4077-9532-eaf5d87fbf0d # Common
handle: fullText
instructions: null
name: 'full text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
