columnSuffix: bjmhcfej
contentColumnType: text
fieldGroup: bf54c795-76da-4077-9532-eaf5d87fbf0d # Common
handle: kaart
instructions: null
name: kaart
searchable: false
settings:
  boundary: '""'
  boundaryRestrictionNELat: null
  boundaryRestrictionNELng: null
  boundaryRestrictionSWLat: null
  boundaryRestrictionSWLng: null
  country: BE
  countryRestriction: null
  height: null
  hideAddress: false
  hideLatLng: null
  hideMap: false
  hideSearch: false
  lat: 51.272154
  lng: 0.514951
  maxZoom: 18.0
  minZoom: 3.0
  showCurrentLocation: false
  showLatLng: false
  showW3WField: false
  showW3WGrid: false
  size: normal
  typeRestriction: null
  zoom: 15
translationKeyFormat: null
translationMethod: none
type: ether\simplemap\fields\MapField
