defaultPlacement: end
enableVersioning: true
handle: blog
name: blog
propagationMethod: all
siteSettings:
  11b80262-63f8-4d25-97a5-994fa355740a: # sport3
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry
    uriFormat: 'blog/{slug}'
type: channel
