defaultPlacement: end
enableVersioning: true
handle: contactPage
name: 'contact page'
propagationMethod: all
siteSettings:
  11b80262-63f8-4d25-97a5-994fa355740a: # sport3
    enabledByDefault: true
    hasUrls: true
    template: contact-page/_entry
    uriFormat: contact-page
type: single
