defaultPlacement: end
enableVersioning: true
handle: logo
name: Logo
propagationMethod: all
siteSettings:
  11b80262-63f8-4d25-97a5-994fa355740a: # sport3
    enabledByDefault: true
    hasUrls: true
    template: logo/_entry
    uriFormat: logo
type: single
