defaultPlacement: end
enableVersioning: true
handle: products
name: products
propagationMethod: all
siteSettings:
  11b80262-63f8-4d25-97a5-994fa355740a: # sport3
    enabledByDefault: true
    hasUrls: true
    template: products/_entry
    uriFormat: 'products/{slug}'
type: channel
