defaultPlacement: end
enableVersioning: true
handle: storeCategories
name: 'store Categories'
propagationMethod: all
siteSettings:
  11b80262-63f8-4d25-97a5-994fa355740a: # sport3
    enabledByDefault: true
    hasUrls: true
    template: store-categories/_entry
    uriFormat: 'store-categories/{slug}'
structure:
  maxLevels: null
  uid: ccc8ce96-3fce-4b01-9f9a-0d31172e7c51
type: structure
